from . import product
from . import stock_transport
from . import stock_transport_journal
from . import stock_transport_line
from . import stock_picking
from . import stock_picking_return
from . import res_config_settings
from . import vendus_supplier
from . import res_partner
from . import res_company
