from . import requests
from . import res_company
from . import res_config_settings
from . import vendus_mixin
from . import vendus_document_mixin
from . import ir_actions_report
from . import res_partner
from . import product
from . import product_category
from . import uom_uom
from . import vendus_model
from . import vendus_uom
from . import vendus_brand
from . import vendus_category
from . import vendus_pricegroup
from . import vendus_payment_method
from . import vendus_user
from . import vendus_account
from . import vendus_register
from . import account_journal
from . import account_move
from . import account_payment
from . import account_tax
from . import account_tax_exemption
from . import res_users
from . import product_pricelist
