from . import pos_payment_method
from . import res_company
from . import res_config_settings
from . import pos_config
from . import pos_order
from . import pos_order_line
from . import pos_payment
from . import pos_session
from . import account_move
from . import vendus_payment_method
